// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/admin/_middleware.ts";
import * as $3 from "./routes/admin/index.tsx";
import * as $4 from "./routes/admin/login.tsx";
import * as $5 from "./routes/api/registers/_middleware.ts";
import * as $6 from "./routes/api/registers/paginate.ts";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/MondayPicker.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/admin/_middleware.ts": $2,
    "./routes/admin/index.tsx": $3,
    "./routes/admin/login.tsx": $4,
    "./routes/api/registers/_middleware.ts": $5,
    "./routes/api/registers/paginate.ts": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/MondayPicker.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
